### ISSUE TITLE
How can I change my account?

### ISSUE THREAD

**Issue by Amet13** [graphcomment/sdk-api-php#1]
Hello.
How can I remove my account or change email/nickname/avatar?
Can you help me with this?

I tried to register on support forum and sent mail to contact[@]graphcomment.com but it's not working so I created issue on GitHub.

**Comment by ddtraceweb** [comment]
Hello,

thanks it's fixed, you can now edit your profile.

**Comment by Amet13** [comment]
@ddtraceweb how can i edit account on graphcomment.com? I do not see any changes.

**Comment by matblandin** [comment]
Dear Amet13,
Go on "My profil", then you can edit.

![image](https://user-images.githubusercontent.com/26900181/32148888-ff9715ce-bcfc-11e7-853d-63b776d00a20.png)

Regards.

**Comment by Amet13** [comment]
I tried to relogin and drop my cookies.
But it's no changes.
![screenshot at 2017-10-30 10-22-59](https://user-images.githubusercontent.com/5184847/32158967-5c6e745e-bd5c-11e7-89bd-ded63c83a58d.png)

Also i tried to login from incognito mode still no changes.

**Comment by matblandin** [comment]
Please, install GraphComment on your website (go on SETUP TAB), then you will find the menu to edit your profil, on your website. We will add the feature to edit your profil into the admin very soon.
Regards.

**Comment by Amet13** [comment]
Thanks.
Can you delete my account manually from service?

**Comment by matblandin** [comment]
Yes of course. It's done.
Can we ask you what possible improvements you would see?
Regards.

**Comment by Amet13** [comment]
Thanks.
At first, edit profile info (email/password), password and other.
Also i can't use your widget on site because of large bottom margin (i have not screenshot for demonstration) but i remember that I can't change this margin and seeing much empty space before footer and comment widget.

**Comment by matblandin** [comment]
Hello Amet, We've fixed the bottom margin to minimum. Now it's really smaller, we resize the height only when you open the Login Popin. About the profil, you have to go on a page of your website after installing GraphComment, and in the very New login popin/button, you will find the link to edit you profil. We are also working to add this option into the admin with a new form. 
Warm regards,
